# Server port configuration
server:
  port: 8080

# Spring Boot configuration
spring:
  # Database connection details
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/petadoption
    username: root  # Consider using environment variables for credentials
    password: password  # Use environment variables or secrets management in production
    driverClassName: com.mysql.cj.jdbc.Driver

  # JPA and Hibernate settings
  jpa:
    hibernate:
      ddl-auto: validate  # Currently set to validate, but duplicated config has update
    show-sql: true
    # Optional: Format SQL logs for better readability
    # properties:
    #   hibernate:
    #     format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

  # Multipart file upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

# Custom application settings
pet:
  upload:
    base-path: D:/petAdaptWebsite/s25-pet-adoption-team-2/pet-adoption-api/uploads