name: Pet Adoption Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      JAVA_HOME: /home/axeljd0sniffers/.sdkman/candidates/java/22.0.2-oracle
      PATH: /home/axeljd0sniffers/.sdkman/candidates/java/22.0.2-oracle/bin:/usr/bin:/bin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3



      - name: Run Unit Tests
        working-directory: pet-adoption-api
        run: ./gradlew test

      - name: Cleanup old Docker resources
        run: |
          docker system prune -a -f --filter "until=24h"

      - name: Build Docker images
        run: |
          docker compose -f docker/ci.docker-compose.yml build

      - name: Deploy application
        run: |
          docker compose -f docker/ci.docker-compose.yml down
          docker compose -f docker/ci.docker-compose.yml up -d --build

      - name: Verify deployment
        run: |
          echo "Checking if containers are running..."
          docker ps
          
          # Wait for services to be fully up
          sleep 15
          
          # Check if frontend is accessible
          curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 || echo "Frontend may not be ready yet"
          
          # Check if backend is accessible
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 || echo "Backend may not be ready yet"
